name: CI

on:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [main]
  schedule:
    # additionally run once per week (At 00:00 on Sunday) to maintain cache
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        cabal: ['3.8']
        ghc:
          - '8.4.4'
          - '8.6.5'
          - '8.8.4'
          - '8.10.7'
          - '9.0.2'
          - '9.2.8'
          - '9.4.7'
          - '9.6.3'
        exclude:
          - os: macOS-latest
            ghc: 9.4.7
          - os: macOS-latest
            ghc: 9.2.8
          - os: macOS-latest
            ghc: 9.0.2
          - os: macOS-latest
            ghc: 8.10.7
          - os: macOS-latest
            ghc: 8.8.4
          - os: macOS-latest
            ghc: 8.6.5
          - os: macOS-latest
            ghc: 8.4.4

          - os: windows-latest
            ghc: 9.4.7
          - os: windows-latest
            ghc: 9.2.8
          - os: windows-latest
            ghc: 9.0.2
          - os: windows-latest
            ghc: 8.10.7
          - os: windows-latest
            ghc: 8.8.4
          - os: windows-latest
            ghc: 8.6.5
          - os: windows-latest
            ghc: 8.4.4

    steps:
      - uses: actions/checkout@v4

      - uses: haskell/actions/setup@v2.3
        id: setup-haskell-cabal
        name: Setup Haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Configure
        run: |
          cabal configure --enable-tests --enable-benchmarks --enable-documentation --test-show-details=direct --write-ghc-environment-files=always

      - name: Freeze
        run: |
          cabal freeze

      - uses: actions/cache@v3
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Install dependencies
        run: |
          cabal build all --only-dependencies

      - name: Build
        run: |
          cabal build all

      - name: Test
        run: |
          cabal test all

      - name: Documentation
        run: |
          cabal haddock

  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ['2.9']
        ghc: ['9.4.7']

    steps:
      - uses: actions/checkout@v4

      - uses: haskell/actions/setup@v2.3
        name: Setup Haskell Stack
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Install dependencies
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: |
          stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: |
          stack test --system-ghc
